package Enums;

public enum Tables {
	characters,
	occupation,
	job,
	characters_and_occupation,
	power,
	characters_and_power,
	organization,
	characters_and_organization,
	school,
	characters_and_school,
	gender,
	characters_and_gender,
	species,
	characters_and_species,
	universe,
	characters_and_universe,
	creator,
	characters_and_creator,
	rank,
	characters_and_rank,
	ethnicity,
	characters_and_ethnicity,
	disease,
	characters_and_disease,
	parent,
	sibling,
	marriage,
	romantic_involvement,
	location,
	place_of_birth;
}
