package Utils;

public enum Tables {
	characters,
	occupation,
	characters_and_occupations,
	power,
	characters_and_powers,
	organization,
	characters_and_organizations,
	school,
	characters_and_schools,
	gender,
	characters_and_genders,
	species,
	characters_and_species,
	universe,
	characters_and_universes,
	creator,
	characters_and_creators,
	rank,
	characters_and_ranks,
	ethnicity,
	characters_and_ethnicities,
	disease,
	characters_and_diseases,
	job,
	location,
	place_of_birth;
}
